name: 'Quality Checks'
on: 
  push:
    branches:
      - main
  pull_request:
    types: ['opened', 'reopened', 'synchronize']
jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha || github.event.push.head.sha }}
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'
      - name: Install dependencies
        run: |
          npm install
          npm test

